name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: docker --version

    - name: Build test image
      run: docker build -t test-app .

    - name: Run pytest inside container
      run: docker run test-app pytest
